### ISSUE TITLE
Same key for Todos Demo?

### ISSUE THREAD

**Issue by ColeTownsend** [pedronauck/reworm#12]
Hey! 

I realize this is a demo, but found a bug when I was playing with the reworm codesandbox. It seems like because the keys are the same this sort of thing happens?

![screenflick movie 31](https://user-images.githubusercontent.com/987654/44528343-50d28500-a6b7-11e8-8d73-8fc36050fa4a.gif)

**Comment by ColeTownsend** [comment]
![screenflick movie 31](https://user-images.githubusercontent.com/987654/44528343-50d28500-a6b7-11e8-8d73-8fc36050fa4a.gif)

**Comment by hnordt** [comment]
The problem is that the key being used is the todo text, so if you repeat the text, you gonna have issues.

@pedronauck it would be better to generate an uniqid and use it instead of the todo text as the key.

```js
let uid = 0

const newTodo = { id: ++uid, text: "Boo" }
```

**Comment by pedronauck** [comment]
I'll do that ✌️
