### ISSUE TITLE
How to read state in non-render methods?

### ISSUE THREAD

**Issue by coodoo** [pedronauck/reworm#14]
For example if I want to read the state and store it in a local variable, is it possible? I've tried to do so in `componentDidMount` as below but to no avail.

```js
componentDidMount() {
  get(s => console.log('state: ', s))
}
```

**Comment by rjoydip-zz** [comment]
Also, it not working in render function. Here is my reproduced code https://stackblitz.com/edit/reworm-issue-14

**Comment by syvpelikaner** [comment]
get is like connect in redux-react, use this
`get(state => <MyComponent state={state}/>)`

Maybe reworm needs subscribe method ?

**Comment by jullicer** [comment]
i think you can only use get when passing props to components.
