### ISSUE TITLE
'yarn build': fails to minify

### ISSUE THREAD

**Issue by robertreppel** [pedronauck/reworm#15]
Using version 1.0.4:
When running "yarn build", I get:

Failed to minify the code from this file: 
 	./node_modules/reworm/dist/reworm.es5.js:32 

There's a link from the error message to https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify .

**Comment by rfoel** [comment]
I'm getting this error using v1.0.4 with npm.

**Comment by rfoel** [comment]
I'm getting this error using v1.0.4 with npm and it breaks my deploys.

**Comment by pedronauck** [comment]
Fixed on v2.0.2
