### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by MioQuispe** [pedronauck/reworm#17]
1. Any plans for async support or examples on how you would do it?
2. Did you abandon this? Would be a shame because I really like the approach!

**Comment by MioQuispe** [comment]
Actually nvm regarding 1. could be good to document it though.
2. Still a bit worrying

**Comment by pedronauck** [comment]
Hi @MioQuispe, sorry but I didn't abandon the project this week I'll release a new version with some new features...

**Comment by MioQuispe** [comment]
@pedronauck Thrilled to hear that!
