### ISSUE TITLE
Ability to use Immer

### ISSUE THREAD

**Issue by ctrlplusb** [pedronauck/reworm#9]
Awesome lib dude.

Would `immer` be supported? As easy as defining the initial state using `immer`?

**Comment by littlehaker** [comment]
I didn't try, but since the `set` method can accept a function, `immer` is supposed to be supported

```js
import produce from "immer"

set(produce(state => {
  state.foo = 'bar'
}))
```

**Comment by pedronauck** [comment]
For sure @littlehaker, this works very well indeed ✌️ 
https://codesandbox.io/s/2jl7o1mwy
